"""App-wide constants."""

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 800
PRIMARY_COLOR = "#2C3E50"
ACTION_COLOR = "#3498DB"
ALERT_COLOR = "#E74C3C"
BACKGROUND_COLOR = "#F5F5F5"

FONT_FAMILY = "Segoe UI"
FONT_HEADING = (FONT_FAMILY, 22, "bold")
FONT_BODY = (FONT_FAMILY, 11)
FONT_BUTTON = (FONT_FAMILY, 11, "bold")
FONT_SMALL = (FONT_FAMILY, 9)

USERNAME_MAX_LENGTH = 50

# Used by auth.SessionTimer and UI event handlers.
INACTIVITY_TIMEOUT_SECONDS = 15 * 60
